---
title: 'Python: Tópicos Miscelaneos  '
---



<u><a href="https://alvarogutyerrez.github.io/alvarogutyerrez/teaching.html"><font color="#ff9900">Back to Teaching</font></a></u>






<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/numpy_intro.ipynb">Sesión #1: Numpy (Numerical Python) </a></h3>
<div class="summary">
<p>
En esta sesión aprenderemos cómo ejecutar operaciones básicas del Álgebra Lineal, haciendo uso de la librería Numpy. Aprenderemos la diferencia entre los objetos _plain python_ y Numpy. De este modo, haciendo uso de operaciones matriciales podremos empezar a trabajar con cálculos numéricos. Al final de la sesión replicaremos la multiplicación matricial haciendo uso de loop anidados.
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/numpy_intro.ipynb">Ir al artículo</a>
</div>
</article>





<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/MasteringPandas.ipynb">Sesión #2: Pandas - Uso del DataFrame  </a></h3>
<div class="summary">
<p>
En esta sesión aprenderemos como ejecutar operaciones básicas de Pandas, y su objeto estrella, el *DataFrame*. Aprenderemos por qué es uno de las objetos preferidos a la hora de programar por los usuarios de python así como la forma más eficiente de llamar celas, filas o columnas específicas. También ocuparemos vizualización de data mediante gráficos simples y prepararemos estadística descriptiva básica.
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/MasteringPandas.ipynb">Ir al artículo</a>
</div>
</article>




<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S03_data_handle.ipynb">Sesión #3: Pandas - Multibase de Datos  </a></h3>
<div class="summary">
<p>
En esta sesión aprenderemos a manejar multiples bases de datos haciendo uso de los comandos _concat_ y _merge_. También trabajaremos con data _jerarquizada_ haciendo uso del la herramienta _group_by_.
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S03_data_handle.ipynb">Ir al artículo</a>
</div>
</article>






<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S04_aplicaciones.ipynb">Sesión #4: Aplicaciones Miscelaneas  </a></h3>
<div class="summary">
<p>
En esta sesión veremos un par de aplicaciones haciendo uso de lo aprendido en las sesiones anteriores. Partiremos con cálculos de _complejidad computacional_, recuperando el tiempo que le toma a nuestro computador realizar ciertas operaciones recursivas. Luego veremos una aplicación financiera usando el comando shift. Finalmente reclasificaremos una variable continua utilizando _bins_ y la función _pd_cut_.
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S04_aplicaciones.ipynb">Ir al artículo</a>
</div>
</article>




<article>
<h3><a href="Tareas/T1/T1_python.html"> <font color="#ff9900">Tarea #1: Complejidad Computacional </font> </a></h3>
<div class="summary">
<p>
Tarea # 1 del curso
</p>
<a class="btn btn-outline-primary btn-sm" href="Tareas/T1/T1_python.html">Ir al artículo</a>
</div>
</article>


<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/Sesion_5_Gradiente_Decendiente.ipynb">Sesión #5: Gradiente Descendiente  </a></h3>
<div class="summary">
<p>
En este apartado, se discutirán tres sabores distintos del algoritmo de *Gradiente Descendiente*. Los cuales, desde el más complejo al más simple, en términos computacionales, van en el siguiente orden: _Batch Gradient Descent_, _Mini-Batch Gradient Descent_ y _Stochastic Gradient Descent_. Veremos ventajas y desventajas de cada uno de estos y también veremos la implementación de estos en la librería _sklearn_. 
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/Sesion_5_Gradiente_Decendiente.ipynb">Ir al artículo</a>
</div>
</article>



<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S06_Metrics.ipynb">Sesión #6: Métricas de Acierto  </a></h3>
<div class="summary">
<p>
En este apartado, se discuten las principales métricas de acierto para los modelos de clasificación. 
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S06_Metrics.ipynb">Ir al artículo</a>
</div>
</article>


<article>
<h3><a href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S07_Modelos_Lineales_Regularizados.ipynb">Sesión #7: Modelos Lineales Regularizados  </a></h3>
<div class="summary">
<p>
En esta sesión, aprenderemos como, haciendo uso de sklearn, estimar modelos de regresión lineal regulariazados (e.g Lasso, Ridge, ElasticNet). Adicional a esto, declararemos una serie de funciones que serán de utilidad en la generación de rezagos en la data (**crealags**), para generar listas ordenadas con todos los modelos que queramos estimar (**creamodelos**),  y finalmente otra que será útil para la presentación de las métricas de desempeño de dichos modelos en cada una de las muestras (**metricas**).
</p>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/alvarogutyerrez/alvarogutyerrez/blob/master/S07_Modelos_Lineales_Regularizados.ipynb">Ir al artículo</a>
</div>
</article>










