---
title: 'Teaching '
---


<article>
<meta charset="utf-8">
<h3><a href="_teaching/intro_stats/Logo/R.pdf"> Introducción a la Estadística  </a></h3>
<div class="summary">
<p>
(Spanish written) El siguiente material de clases tiene por objetivo entregar herramienta de visualización de los distintos tópicos cubiertos por el curso, pero por ningún motivo intenta reemplazar el estudio riguroso y constante de la bibliografía del mismo.
</p>
<a class="btn btn-outline-primary btn-sm" href="_teaching/intro_stats/Logo/R.pdf">Revisar los Contenidos</a>
</div>
</article>


<article>
<meta charset="utf-8">
<h3><a href="_teaching/stata_eco_fin/main/taller_stata_intro.html"> Stata-$\LaTeX$  Combo  </a></h3>
<div class="summary">
<p>
(Spanish written) El siguiente material fue preparado como parte de un taller sobre el uso conjunto de Stata y $\LaTeX$ para los alumnos del Magister de Finanzas dentro de su curso de Econometría Financiera.
</p>
<a class="btn btn-outline-primary btn-sm" href="_teaching/stata_eco_fin/main/taller_stata_intro.html">Ir al Post</a>
</div>
</article>




<article>
<meta charset="utf-8">
<h3><a href="_teaching/python/python_clases/python_intro.html"> Introducción a Python  </a></h3>
<div class="summary">
<p>
(Spanish Written) Acá podrás encontrar una breve brevísima introducción a Python con ciertas aplicaciones financieras.
</p>
<a class="btn btn-outline-primary btn-sm" href="_teaching/python/python_clases/python_intro.html">Ir al post</a>
</div>
</article>




<article>
<meta charset="utf-8">
<h3><a href="_teaching/python/main/python_main.html"> Python for Track Record Strategies  </a></h3>
<div class="summary">
<p>
Here you can find some random (but I hope usefull) function that you can implement easily on your scripts for your own purposes.
</p>
<a class="btn btn-outline-primary btn-sm" href="_teaching/python/main/python_main">Go to Post</a>
</div>
</article>



